### PR TITLE
main.js: Improve dark mode

### PR DESCRIPTION
**Pull request by noelleleigh**
Make use of the [`color-scheme` meta tag][0] to style buttons and other  widgets to match the selected color scheme.

When the scheme is toggled, the `content` of the tag is set to "light"  or "dark" to tell the user agent how to theme input elements, which  should match the colors of the rest of the app.

Here's a screenshot on Firefox with the dark mode changes:

The Trunkless app in dark mode, with its buttons also styled with dark backgrounds

[0]: https://html.spec.whatwg.org/multipage/semantics.html#meta-color-scheme

### CODE REVIEW

**Review by vilmibm — APPROVED** [review]
nice! thank you!

**Comment by noelleleigh** [comment]
> nice! thank you!

No problem! Do you want to merge it?

**Comment by noelleleigh** [comment]
Seems like this patch hasn't been deployed on <https://trunkless.tilde.town/> yet?

**Comment by vilmibm** [comment]
it is finally deployed

**Pull request merged**
